---
abstract: 'Non-blocking and streaming capable template engine'
author:
  - 'Viacheslav Tykhanovskyi <vti@cpan.org>'
build_requires: {}
configure_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-APL
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Test::More: 0
  perl: 5.008007
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/vti/text-apl
version: 0.01
